name: fleet_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  rxdart: ^0.27.1
  freezed_annotation: ^0.14.2
  universal_html: ^2.0.8
  path_provider: ^2.0.2
  share_plus: ^2.1.4

dev_dependencies:
  test: ^1.17.11
  build_runner: ^2.1.1
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/NotoColorEmoji.ttf
    - family: NotoSansCJK
      fonts:
        - asset: assets/NotoSansCJKjp-Regular.otf
